"""empty message

Revision ID: 0129d8e00d3e
Revises: 122a8f4250e4
Create Date: 2019-01-11 14:20:45.284678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0129d8e00d3e'
down_revision = '122a8f4250e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_teammember', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_teammember', 'active')
    # ### end Alembic commands ###
