"""add-i18n-key-and-value

Revision ID: 2247777f3e5c
Revises: 61732aec8302
Create Date: 2018-12-02 20:00:39.671273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2247777f3e5c'
down_revision = '61732aec8302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i18n_key',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('desc', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desc')
    )
    op.create_table('i18n_value',
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('locale_id', sa.String(length=16), nullable=False),
    sa.Column('gloss', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['i18n_key.id'], ),
    sa.ForeignKeyConstraint(['locale_id'], ['i18n_locale.id'], ),
    sa.PrimaryKeyConstraint('key_id', 'locale_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('i18n_value')
    op.drop_table('i18n_key')
    # ### end Alembic commands ###
