"""empty message

Revision ID: 281afdb72914
Revises: 128ce2077adf
Create Date: 2019-01-08 22:40:49.028864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281afdb72914'
down_revision = '128ce2077adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_i18n', sa.String(length=5), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_account_role',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['people_account.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['people_role.id'], )
    )
    op.drop_table('roles_role')
    op.drop_constraint(None, 'groups_member', type_='foreignkey')
    op.create_foreign_key(None, 'groups_member', 'people_role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups_member', type_='foreignkey')
    op.create_foreign_key(None, 'groups_member', 'roles_role', ['role_id'], ['id'])
    op.create_table('roles_role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_i18n', sa.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('people_account_role')
    op.drop_table('people_role')
    # ### end Alembic commands ###
