"""add-locale

Revision ID: 61732aec8302
Revises: 
Create Date: 2018-12-02 19:10:03.935287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61732aec8302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i18n_locale',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('desc', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('i18n_locale')
    # ### end Alembic commands ###
