"""move-language

Revision ID: 9948c6861906
Revises: c816d0cedf07
Create Date: 2018-12-19 13:43:39.875364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9948c6861906'
down_revision = 'c816d0cedf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i18n_language',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_i18n', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['name_i18n'], ['i18n_key.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.drop_table('i18n_language_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i18n_language_code',
    sa.Column('code', sa.VARCHAR(length=2), nullable=False),
    sa.Column('name', sa.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('i18n_language')
    # ### end Alembic commands ###
