"""language-country-codes

Revision ID: e516827aa4f0
Revises: 7e8214911837
Create Date: 2018-12-17 16:22:13.902433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e516827aa4f0'
down_revision = '7e8214911837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i18n_country_code',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('i18n_language_code',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('i18n_language_code')
    op.drop_table('i18n_country_code')
    # ### end Alembic commands ###
