"""empty message

Revision ID: e91c9398021a
Revises: 6bd142e99d95
Create Date: 2019-01-11 10:05:39.974452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91c9398021a'
down_revision = '6bd142e99d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses_course_offering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses_course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses_prerequisite',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prereq_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses_course.id'], ),
    sa.ForeignKeyConstraint(['prereq_id'], ['courses_course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'prereq_id')
    )
    op.drop_table('events_teams')
    op.drop_table('events_event')
    op.drop_table('events_asset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_asset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.ForeignKeyConstraint(['location_id'], ['places_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('start', sa.DATETIME(), nullable=False),
    sa.Column('end', sa.DATETIME(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.ForeignKeyConstraint(['location_id'], ['places_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events_teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('courses_prerequisite')
    op.drop_table('courses_course_offering')
    op.drop_table('courses_course')
    # ### end Alembic commands ###
